#!/bin/bash
echo "Building the project"
config-pin p9.12 gpio
config-pin p8.16 gpio_pu
g++ -Wall publish.cpp GPIO.cpp -o publish -lpaho-mqtt3c -pthread
g++ -Wall subscribe.cpp GPIO.cpp -o subscribe -lpaho-mqtt3c -pthread
g++ -Wall pushbutton.cpp GPIO.cpp -o pushbutton -lpaho-mqtt3c -pthread
echo "Finished"

